- images.js
- queries/events.js
Signed-off-by: Agnaldo Junior <agnaldo.junior01@gmail.com>
> Add lock mechanism to image downloader and debug for jobs

- dashboard/package-lock.json
- dashboard/package.json
- dashboard/src/App.tsx
- dashboard/src/routes.tsx
- dashboard/src/shared/utils.ts
- dashboard/tsconfig.json
> Create routing system for Dashboard.

- server/bin/start.js
- server/docker/docker-compose.yml
- server/package-lock.json
- server/package.json
- server/src/helpers/logger.js
- server/src/interfaces/api/api.js
- server/src/interfaces/api/index.js
- server/src/interfaces/api/nodemon.json
Closes #83.
- Setup api interface skeleton
- Add express
- Update bin scripta to be more compliant with nodemon
- Add morgan logging
> Create basic http interface for API

- devenv/ctl.sh
- server/package-lock.json
- server/package.json
- server/src/interfaces/api/api.js
- server/src/interfaces/api/controllers/settings.js
- server/src/interfaces/api/helpers/swagger.js
- server/src/interfaces/api/index.js
- server/src/interfaces/api/nodemon.json
- server/src/interfaces/api/routes/index.js
- server/src/interfaces/api/routes/settings.js
- server/src/services/settings.js
Fixes #95 
- Add body parser package
- Create route system and add settings route to it
> Implement Endpoints for Settings

- devenv/nginx/default.conf
- server/src/adapters/albionApiClient.js
- server/src/interfaces/api/controllers/battles.js
- server/src/interfaces/api/helpers/cache.js
- server/src/interfaces/api/routes/battles.js
- server/src/interfaces/api/routes/settings.js
- server/src/ports/albion.js
- server/src/services/battles.js
- Add endpoints for battles
- Prepare API for nginx cache
- Add cache support for api in nginx settings
Fixes #94
> Implement endpoint for Battle data

- dashboard/Dockerfile
- dashboard/Dockerfile.dev
- dashboard/package-lock.json
- dashboard/package.json
- dashboard/src/App.tsx
- dashboard/src/__tests__/App.test.jsx
- dashboard/src/__tests__/__snapshots__/App.test.jsx.snap
- dashboard/src/index.tsx
- dashboard/src/pages/Home.tsx
- dashboard/src/routes.tsx
- dashboard/src/styles/global-styles.tsx
- dashboard/tsconfig.json
- devenv/ctl.sh
- devenv/docker-compose.yml
Add material UI to the project, Home page contains some button and grid examples to verify it's working.
Fixes #103
> Add material ui to the project

- dashboard/src/pages/Server/index.tsx
- dashboard/src/pages/Settings/index.tsx
- dashboard/src/pages/Track/index.tsx
- dashboard/src/shared/components/Loader/index.tsx
- dashboard/src/shared/components/Toast/index.tsx
- dashboard/src/shared/theme.tsx
- dashboard/src/store/api.ts
- dashboard/src/store/index.ts
- dashboard/src/store/track.ts
- dashboard/src/styles/app-styles.tsx
- dashboard/src/styles/global-styles.tsx
- Initial track implementation
- Add store for search
- Minor layout adjusts
- Initial version of tracking screen
> Track screen

- .github/workflows/dashboard-ci.yml
- .github/workflows/server-ci.yml
- dashboard/src/components/Footer/index.tsx
- dashboard/src/components/Header/index.tsx
- dashboard/src/components/Header/styles.tsx
- dashboard/src/pages/Dashboard/styles.tsx
- Add header for mobile
- Fix dashboard padding
- Fix mobile version of footer
Fixes #124
> Add mobile responsiveness

- devenv/ctl.sh
- server/src/adapters/awsSdkClient.js
- server/src/adapters/itemCDNClient.js
- server/src/helpers/tracking.js
- server/src/helpers/utils.js
- server/src/interfaces/bot/bot.js
- server/src/interfaces/bot/controllers/events.js
- server/src/ports/albion.js
- server/src/services/rankings.js
- Improve ctl restart command
- Fix AWS isEnabled property
- Fix missing track collection refactor on addRanking settings
- Fix download CDN making bot stuck
Fixes #129
> Fix issue with bot stuck in downloading image

- dashboard/src/components/Header.tsx
- dashboard/src/components/ServerCard.tsx
- dashboard/src/components/styles/Header.tsx
- dashboard/src/components/styles/ServerCard.tsx
- dashboard/src/pages/Premium.tsx
- dashboard/src/pages/Subscription.tsx
- dashboard/src/pages/styles/Premium.tsx
- dashboard/src/styles/index.tsx
- Organize mobile and desktop header
- Fix admin server list on mobile
- Fix Premium list on mobile
Fixes #158
> fix: Fix mobile dashboard lists

- server/src/interfaces/bot/controllers/rankings.js
- server/src/services/rankings.js
> Fix clear rankings for servers

- server/.env.example
- server/src/helpers/utils.js
- server/src/interfaces/bot/bot.js
- server/src/interfaces/bot/controllers/battles.js
- server/src/interfaces/bot/controllers/events.js
- server/src/interfaces/crawler/controllers/battles.js
- server/src/interfaces/crawler/controllers/events.js
- Add debug logs to util interval functions
- Update the way bots are initialized
- Organize .env.example, add batch queue ft
- crawler: Add the ability to publish events/battles in batch
- Make bot support batch queues
Fixes #(issue)
> Feature: batch queues

- server/src/helpers/embeds.js
- server/src/helpers/logger.js
- server/src/helpers/utils.js
- server/src/interfaces/bot/commands/help.js
* fixed issue with passing negative values to `.repeat()`
* created reusable `printSpace` util
* used `printSpace` util whenever `" ".repeat()` was used
Fixes #182
> Fix passing invalid count value to `.repeat()` method

- server/src/helpers/logger.js
- server/src/interfaces/bot/controllers/battles.js
- server/src/interfaces/bot/controllers/events.js
- server/src/interfaces/bot/controllers/notifications.js
- server/src/ports/adapters/itemCDNClient.js
- Improve logging metadata in events/battles
- Add log metadata to CDN download
- Update logging for notifications
Fixes #149
> 149 logs meta

- server/.env.example
- server/src/interfaces/api/controllers/subscriptions.js
- server/src/interfaces/api/index.js
- server/src/interfaces/bot/controllers/subscriptions.js
- server/src/ports/adapters/discordApiClient.js
- server/src/ports/database.js
- server/src/ports/discord.js
- server/src/services/images.js
- server/src/services/servers.js
- server/src/services/subscriptions.js
- Refactor subscription service
- Add discord community premium role env variable
- Add method to regularly check for Premium Users
- Add hooks to add/remove user roles when subscribed with stripe
Fixes #137
> feat: Add Premium User roles to the Community Server

- server/src/helpers/scheduler.js
> feat: Add timeout removers

- dashboard/src/components/ServerList.tsx
- dashboard/src/pages/Admin.tsx
- dashboard/src/styles/index.tsx
> feat: Add pagination to Server Admin

- server/src/ports/adapters/albionDataApiClient.js
- server/src/ports/albion.js
> feat: Fetch loot value from East server

- dashboard/src/pages/PremiumPage.tsx
- dashboard/src/pages/Subscription.tsx
- dashboard/src/routes.tsx
- server/src/interfaces/api/webhooks/stripe.js
- Rename PremiumPage
- Add more exception clauses for stripe webhook
- Update webhook logger metadata
> chore: Cleanup Premium logic

- dashboard/src/components/Header.tsx
- dashboard/src/types.ts
- server/src/helpers/discord.js
- server/src/interfaces/api/routes/users.js
- [BE] Update user fields according to discords latest user policy
- [FE] Update user fields according to discords latest user policy
> chore: Update discord user fields

- albion-killbot.code-workspace
- dashboard/src/components/SettingsBattles.tsx
- dashboard/src/pages/DashboardPage.tsx
- dashboard/src/pages/HomePage.tsx
- dashboard/src/routes.tsx
- dashboard/src/store/settings.ts
- dashboard/src/types.ts
- server/migrations/1686601142550-add-battles-threshold.js
- server/src/helpers/tracking.js
- server/src/helpers/utils.js
- server/src/interfaces/api/routes/servers.js
- server/src/interfaces/bot/controllers/battles.js
- server/src/services/settings.js
- server/src/services/track.js
- Add threshold filter to bot battles controller
- Update api router docs
- Rename Dashboard to DashboardPage
- Rename Home to HomePage
- Add i18n editor as workspace recommended plugins for vscode
- Add battle threshold settings in dashboard
- Add threshold to the default settings.battles
> feat: Battle minimum threshold

- dashboard/src/pages/ServerPage.tsx
- server/src/assets/locales/en.json
- server/src/assets/locales/es.json
- server/src/assets/locales/fr.json
- server/src/assets/locales/pt.json
- server/src/assets/locales/ru.json
- server/src/interfaces/bot/commands/subscription.js
- server/src/interfaces/bot/controllers/notifications.js
- server/src/interfaces/bot/controllers/subscriptions.js
- server/src/services/subscriptions.js
- Add subscription expired notice to dashboard
- Make user notify the subscription owner that a subscription has expired.
> feat: Subscription expire notice

- dashboard/src/components/TrackItemOptions.tsx
- dashboard/src/store/track.ts
- dashboard/src/types.ts
- server/migrations/1692561101245-track-customize.js
- server/src/interfaces/api/routes/servers.js
- server/src/interfaces/bot/controllers/events.js
- Add migration to the new file structure
- Update bot to use tracking customizations
- Update api swagger docs
- Update dashboard to accept new customization features
> feat: Improve tracking customization

- dashboard/src/components/SettingsBattles.tsx
- dashboard/src/components/SettingsDeaths.tsx
- dashboard/src/components/SettingsKills.tsx
- dashboard/src/helpers/constants.ts
- dashboard/src/store/api.ts
- dashboard/src/store/settings.ts
- dashboard/src/types.ts
- server/src/assets/locales/en.json
- server/src/assets/locales/es.json
- server/src/assets/locales/fr.json
- server/src/assets/locales/pt.json
- server/src/assets/locales/ru.json
- server/src/helpers/constants.js
- server/src/helpers/embeds.js
- server/src/interfaces/api/routes/constants.js
- server/src/interfaces/api/routes/servers.js
- server/src/interfaces/bot/commands/settings.js
- server/src/interfaces/bot/controllers/battles.js
- server/src/interfaces/bot/controllers/events.js
- server/src/services/settings.js
- Move REPORT_MODES to the constants file
- Add feature to set link providers in bot
- Update API docs
- Create api request to retrieve servers constants
- Add link providers feature to dashboard
> feat: Choose provider for links

- server/src/helpers/cache.js
- server/src/ports/discord.js
> feat: Cache auto-refresh option for memoize

- server/src/helpers/albion.js
- server/src/interfaces/bot/controllers/events.js
- server/src/ports/albion.js
> Debug loot value

- server/src/config/default.js
- server/src/interfaces/api/webhooks/stripe.js
- server/src/interfaces/bot/controllers/subscriptions.js
- server/src/ports/stripe.js
- server/src/services/subscriptions.js
- Upgrade stripe apiVersion
- Consolidate stripe hooks to function better
> fix: stripe webhooks issue

- .github/workflows/deploy.yml
> Update deploy script to replace SSH script

- dashboard/src/helpers/theme.ts
- server/src/config/default.js
- server/src/helpers/albion.js
- server/src/helpers/constants.js
- server/src/helpers/embeds.js
- server/src/ports/adapters/albionApiClient.js
- server/src/ports/adapters/albionDataApiClient.js
> Add europe server

- server/src/helpers/constants.js
> Fix links for albion2d provider

- server/src/interfaces/crawler/controllers/rankings.js
- server/src/services/rankings.js
> Update clear rankings routine
